[package]
name = "merk"
description = "Merkle key/value store"
version = "0.2.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
time = "0.1.42"
rocksdb = "0.12.2"
rand = "0.6.5"
hex = "0.3.2"
serde_derive = "1.0.91"
bincode = "1.1.4"
serde = "1.0.91"
colored = "1.8.0"
num_cpus = "1.10.0"
error-chain = "0.12.1"
tempfile = "3.1.0"

[dependencies.blake2-rfc]
version = "0.2.18"
features = ["bench", "simd_asm"]
